### ISSUE TITLE
Categorical tensor product of von Neumann algebras

### ISSUE THREAD

**Issue by awesterb** [westerbaan/theses#26]
One difference between the categorical tensor product and the (regular) spacial one is that the product states need not separate the points (by an adaptation of Lemma 18 of [Duplicable von Neumann algebras](http://bram.westerbaan.name/duplicable-von-neumann-algebras.pdf)).

**Comment by bwesterb** [comment]
As a reminder: the state that is normal on the categorical tensor (but is not in the spatial) is `a (x) b |-> integral ab`
