### ISSUE TITLE
Ultranorm continuity and B-linearity

### ISSUE THREAD

**Issue by bwesterb** [westerbaan/theses#46]
A bounded B-linear map is ultranorm continuous.  Is there a converse?

**Comment by awesterb** [comment]
An ultranorm continuous linear map between pre-Hilbert C*-modules need not be a module map.  Indeed,  given an element a of a von Neumann algebra B the ultrastrongly continuous map a* ( . ) a from B to B is ultranormly continuous, but (depending on B) might not be a module map, c.q. be of the form  c ( . ) for some c from B.

**Comment by bwesterb** [comment]
Ja, derp :).

**Comment by awesterb** [comment]
It is still possible that an ultranorm continuous module map between (self-dual) pre-Hilbert C*-modules is bounded.
